In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
import os

In [4]:
os.chdir("/Users/subinpark2/Downloads/ST47/")

In [5]:
%ls

ST_brian.table.csv  dic3.csv

In [92]:
#df1=pd.read_csv("ST_brian.table.csv")
df2=pd.read_csv("dic3.csv",header=None,sep='\t')

In [89]:
#df1.head()
#type(df1['Assembly'])
df1['Assembly']=df1['Assembly'].apply(lambda x:x.split("_")[0]+x.split("_")[1])

In [90]:
df1.head()

,Assembly,ST,allele,allele.1,allele.2,allele.3,allele.4,allele.5,allele.6,?,?.1
0,GCF900048925,1.0,flaA-1,pilE-4,asd-3,mip-1,mompS-1,proA-1,neuA_neuAH-1,NaN,NaN
1,GCF900049255,1.0,flaA-1,pilE-4,asd-3,mip-1,mompS-1,proA-1,neuA_neuAH-1,NaN,NaN
2,GCF900050175,NaN,flaA-1,pilE-4,asd-3,mip-1,mompS-1,proA-1,neuA_neuAH-14,NaN,NaN
3,GCF900050205,1.0,flaA-1,pilE-4,asd-3,mip-1,mompS-1,proA-1,neuA_neuAH-1,NaN,NaN
4,GCF900050235,1.0,flaA-1,pilE-4,asd-3,mip-1,mompS-1,proA-1,neuA_neuAH-1,NaN,NaN

In [93]:
df2.head()

                         0                                                  1
0  GCF900051665.blast.pair  ['lpg0577_1', 'lpg1830_1', 'lpg1566_1', 'lpg22...
1  GCF900063035.blast.pair  ['lpg0577_1', 'lpg1830_1', 'lpg1566_1', 'lpg22...
2  GCF900054665.blast.pair  ['lpg0577_2', 'lpg1830_12', 'lpg1566_2', 'lpg2...
3  GCF900064765.blast.pair  ['lpg0577_2', 'lpg1830_12', 'lpg1566_2', 'lpg2...
4  GCF900062695.blast.pair  ['lpg0577_2', 'lpg1830_12', 'lpg1566_2', 'lpg2...

In [95]:
df2.columns=['Assembly','subtype']

In [96]:
df2['Assembly']=df2['Assembly'].apply(lambda x :x.split(".")[:1])

In [97]:
df2['Assembly']=df2['Assembly'].map(lambda x: str(x)[:-2])
df2['Assembly']=df2['Assembly'].map(lambda x: str(x)[2:])

In [98]:
df2.head()

       Assembly                                            subtype
0  GCF900051665  ['lpg0577_1', 'lpg1830_1', 'lpg1566_1', 'lpg22...
1  GCF900063035  ['lpg0577_1', 'lpg1830_1', 'lpg1566_1', 'lpg22...
2  GCF900054665  ['lpg0577_2', 'lpg1830_12', 'lpg1566_2', 'lpg2...
3  GCF900064765  ['lpg0577_2', 'lpg1830_12', 'lpg1566_2', 'lpg2...
4  GCF900062695  ['lpg0577_2', 'lpg1830_12', 'lpg1566_2', 'lpg2...

In [149]:
df3=pd.DataFrame(df2['subtype'].value_counts())
df3.reset_index(level=0, inplace=True)

In [152]:
df3.columns=['subtype','count']
df3['subnumber']=df3.index

In [153]:
df3.head()

                                             subtype  count  subnumber
0  ['lpg0577_2', 'lpg1830_12', 'lpg1566_2', 'lpg2...     55          0
1  ['lpg0577_2', 'lpg1830_12', 'lpg1566_2', 'lpg2...     29          1
2  ['lpg0577_11', 'lpg1830_11', 'lpg1566_10', 'lp...     28          2
3  ['lpg0577_11', 'lpg1830_11', 'lpg1566_10', 'lp...     13          3
4  ['lpg0577_2', 'lpg1830_17', 'lpg1566_15', 'lpg...     11          4

In [ ]:
pd.merge(df1,df3,on='Assembly')

In [157]:
df2.drop("subnumber",axis=1)

         Assembly                                            subtype
0    GCF900051665  ['lpg0577_1', 'lpg1830_1', 'lpg1566_1', 'lpg22...
1    GCF900063035  ['lpg0577_1', 'lpg1830_1', 'lpg1566_1', 'lpg22...
2    GCF900054665  ['lpg0577_2', 'lpg1830_12', 'lpg1566_2', 'lpg2...
3    GCF900064765  ['lpg0577_2', 'lpg1830_12', 'lpg1566_2', 'lpg2...
4    GCF900062695  ['lpg0577_2', 'lpg1830_12', 'lpg1566_2', 'lpg2...
5    GCF900057605  ['lpg0577_2', 'lpg1830_12', 'lpg1566_2', 'lpg2...
6    GCF900054685  ['lpg0577_2', 'lpg1830_12', 'lpg1566_2', 'lpg2...
7    GCF900063835  ['lpg0577_2', 'lpg1830_12', 'lpg1566_2', 'lpg2...
8    GCF900062535  ['lpg0577_2', 'lpg1830_12', 'lpg1566_2', 'lpg2...
9    GCF900058835  ['lpg0577_2', 'lpg1830_12', 'lpg1566_2', 'lpg2...
10   GCF900062665  ['lpg0577_2', 'lpg1830_12', 'lpg1566_2', 'lpg2...
11   GCF900063145  ['lpg0577_2', 'lpg1830_12', 'lpg1566_2', 'lpg2...
12   GCF900059595  ['lpg0577_2', 'lpg1830_12', 'lpg1566_2', 'lpg2...
13   GCF900062735  ['lpg0577_2', 'lpg1830_12', 'lpg1566_2', 'lpg2...
14   GCF900063865  ['lpg0577_2', 'lpg1830_12', 'lpg1566_2', 'lpg2...
15   GCF900050245  ['lpg0577_2', 'lpg1830_12', 'lpg1566_2', 'lpg2...
16   GCF900064335  ['lpg0577_2', 'lpg1830_17', 'lpg1566_13', 'lpg...
17   GCF900057615  ['lpg0577_2', 'lpg1830_12', 'lpg1566_2', 'lpg2...
18   GCF900060775  ['lpg0577_2', 'lpg1830_12', 'lpg1566_2', 'lpg2...
19   GCF900054385  ['lpg0577_2', 'lpg1830_12', 'lpg1566_2', 'lpg2...
20   GCF900048965  ['lpg0577_2', 'lpg1830_12', 'lpg1566_2', 'lpg2...
21   GCF900061675  ['lpg0577_2', 'lpg1830_17', 'lpg1566_15', 'lpg...
22   GCF900063845  ['lpg0577_2', 'lpg1830_12', 'lpg1566_2', 'lpg2...
23   GCF900054695  ['lpg0577_2', 'lpg1830_17', 'lpg1566_13', 'lpg...
24   GCF900062525  ['lpg0577_2', 'lpg1830_12', 'lpg1566_2', 'lpg2...
25   GCF900064755  ['lpg0577_2', 'lpg1830_12', 'lpg1566_2', 'lpg2...
26   GCF900064315  ['lpg0577_2', 'lpg1830_12', 'lpg1566_2', 'lpg2...
27   GCF900060425  ['lpg0577_2', 'lpg1830_12', 'lpg1566_2', 'lpg2...
28   GCF900053435  ['lpg0577_2', 'lpg1830_12', 'lpg1566_2', 'lpg2...
29   GCF900060435  ['lpg0577_2', 'lpg1830_12', 'lpg1566_2', 'lpg2...
..            ...                                                ...
308  GCF900061935  ['lpg0577_11', 'lpg1830_11', 'lpg1566_10', 'lp...
309  GCF900057775  ['lpg0577_11', 'lpg1830_11', 'lpg1566_10', 'lp...
310  GCF900062385  ['lpg0577_11', 'lpg1830_11', 'lpg1566_10', 'lp...
311  GCF900052285  ['lpg0577_11', 'lpg1830_11', 'lpg1566_10', 'lp...
312  GCF900063825  ['lpg0577_11', 'lpg1830_11', 'lpg1566_10', 'lp...
313  GCF900060765  ['lpg0577_11', 'lpg1830_11', 'lpg1566_10', 'lp...
314  GCF900060695  ['lpg0577_12', 'lpg1830_11', 'lpg1566_10', 'lp...
315  GCF900060705  ['lpg0577_12', 'lpg1830_11', 'lpg1566_10', 'lp...
316  GCF900064175  ['lpg0577_12', 'lpg1830_11', 'lpg1566_10', 'lp...
317  GCF900064725  ['lpg0577_13', 'lpg1830_2', 'lpg1566_3', 'lpg2...
318  GCF900062495  ['lpg0577_13', 'lpg1830_2', 'lpg1566_3', 'lpg2...
319  GCF900057245  ['lpg0577_13', 'lpg1830_2', 'lpg1566_3', 'lpg2...
320  GCF900065315  ['lpg0577_13', 'lpg1830_2', 'lpg1566_3', 'lpg2...
321  GCF900053415  ['lpg0577_13', 'lpg1830_2', 'lpg1566_3', 'lpg2...
322  GCF900056655  ['lpg0577_13', 'lpg1830_2', 'lpg1566_3', 'lpg2...
323  GCF900061465  ['lpg0577_13', 'lpg1830_2', 'lpg1566_3', 'lpg2...
324  GCF900062505  ['lpg0577_13', 'lpg1830_2', 'lpg1566_3', 'lpg2...
325  GCF900063055  ['lpg0577_13', 'lpg1830_2', 'lpg1566_3', 'lpg2...
326  GCF900053365  ['lpg0577_13', 'lpg1830_2', 'lpg1566_3', 'lpg2...
327  GCF900049265  ['lpg0577_13', 'lpg1830_4', 'lpg1566_3', 'lpg2...
328  GCF900070135  ['lpg0577_13', 'lpg1830_2', 'lpg1566_3', 'lpg2...
329  GCF900054405  ['lpg0577_13', 'lpg1830_2', 'lpg1566_3', 'lpg2...
330  GCF900062515  ['lpg0577_13', 'lpg1830_2', 'lpg1566_3', 'lpg2...
331  GCF900070185  ['lpg0577_13', 'lpg1830_2', 'lpg1566_3', 'lpg2...
332  GCF900050185  ['lpg0577_14', 'lpg1830_8', 'lpg1566_3', 'lpg2...
333  GCF900059945  ['lpg0577_15', 'lpg1830_12', 'lpg1566_2', 'lpg...
334  GCF900056925  ['lpg0577_15', 'lpg1830_12', 'lpg1566_2', 'lpg...
335  GCF900061525  ['lpg0577_15', 'lpg1830_12', 'lpg1566_2', 'lpg...
336  GCF900048935  ['lpg0577_16', 'lpg1830_13', 'lpg1566_2', 'lpg...
337  GCF900053355  ['lpg0577_16', 'lpg1830_13', 'lpg1566_2', 'lpg...

[338 rows x 2 columns]

In [160]:
df4=pd.merge(df2,df3,on='subtype')

In [165]:
df4=df4.drop('subnumber_x',axis=1)

In [208]:
df5=pd.merge(df1,df4,on='Assembly')

In [168]:
df5.to_csv('compare_blast_50gene_st47.csv')

In [209]:
df5.head()

,Assembly,ST,allele,allele.1,allele.2,allele.3,allele.4,allele.5,allele.6,?,?.1,subtype,count,subnumber_y
0,GCF900048925,1.0,flaA-1,pilE-4,asd-3,mip-1,mompS-1,proA-1,neuA_neuAH-1,NaN,NaN,"['lpg0577_3', 'lpg1830_4', 'lpg1566_8', 'lpg22...",1,62
1,GCF900049255,1.0,flaA-1,pilE-4,asd-3,mip-1,mompS-1,proA-1,neuA_neuAH-1,NaN,NaN,"['lpg0577_3', 'lpg1830_15', 'lpg1566_8', 'lpg2...",2,39
2,GCF900050175,NaN,flaA-1,pilE-4,asd-3,mip-1,mompS-1,proA-1,neuA_neuAH-14,NaN,NaN,"['lpg0577_3', 'lpg1830_15', 'lpg1566_8', 'lpg2...",2,27
3,GCF900050205,1.0,flaA-1,pilE-4,asd-3,mip-1,mompS-1,proA-1,neuA_neuAH-1,NaN,NaN,"['lpg0577_3', 'lpg1830_15', 'lpg1566_8', 'lpg2...",3,22
4,GCF900050235,1.0,flaA-1,pilE-4,asd-3,mip-1,mompS-1,proA-1,neuA_neuAH-1,NaN,NaN,"['lpg0577_3', 'lpg1830_15', 'lpg1566_8', 'lpg2...",2,39

In [213]:
df6=df5['subtype'].str.split(',', expand=True)

In [ ]:
df5[['Assembly','subtype']]

In [217]:
df6=df5['subtype'].str.split(',', expand=True).rename(columns = lambda x: "allele"+str(x+1))

In [219]:
df6.to_csv('allele_seperate.csv')

In [221]:
df6 = df6.rename(columns={col: col.split('_')[0] for col in df6.columns})

In [231]:
df6.head(

,allele1,allele2,allele3,allele4,allele5,allele6,allele7,allele8,allele9,allele10,...,allele37,allele38,allele39,allele40,allele41,allele42,allele43,allele44,allele45,allele46
0,['lpg0577_3','lpg1830_4','lpg1566_8','lpg2231_9','lpg2339_4','lpg2516_13','lpg0287_11','lpg1398_11','lpg1737_2','lpg2461_11',...,'lpg0785_10','lpg0330_4','lpg1340_4','lpg0078_12','lpg1452_9','lpg0712_8','lpg1178_15','lpg2039_12','lpg1994_18'],None
1,['lpg0577_3','lpg1830_15','lpg1566_8','lpg2231_9','lpg2339_4','lpg2516_13','lpg0287_11','lpg1398_11','lpg1737_2','lpg2461_11',...,'lpg0785_10','lpg0330_4','lpg1340_4','lpg0078_12','lpg1452_9','lpg0712_5','lpg1178_15','lpg2039_12','lpg1994_17'],None
2,['lpg0577_3','lpg1830_15','lpg1566_8','lpg2231_9','lpg2339_4','lpg2516_14','lpg0287_10','lpg1398_11','lpg1737_2','lpg2461_9',...,'lpg0785_14','lpg0330_4','lpg1340_4','lpg0078_12','lpg1452_9','lpg0712_8','lpg1178_12','lpg2039_12','lpg1994_17'],None
3,['lpg0577_3','lpg1830_15','lpg1566_8','lpg2231_9','lpg2339_4','lpg2516_13','lpg0287_11','lpg1398_11','lpg1737_2','lpg2461_11',...,'lpg0116_2','lpg0785_10','lpg0330_4','lpg1340_4','lpg0078_12','lpg1452_9','lpg0712_8','lpg1178_15','lpg2039_12','lpg1994_17']
4,['lpg0577_3','lpg1830_15','lpg1566_8','lpg2231_9','lpg2339_4','lpg2516_13','lpg0287_11','lpg1398_11','lpg1737_2','lpg2461_11',...,'lpg0785_10','lpg0330_4','lpg1340_4','lpg0078_12','lpg1452_9','lpg0712_5','lpg1178_15','lpg2039_12','lpg1994_17'],None

In [241]:
line=open('new_50gene.list')
header=print('\t')

In [245]:
df2=df2.drop('subnumber',axis=1)

In [263]:
dic={}
for i in df2['Assembly']:
     for j in df2['subtype']:
         dic[i]=j

#dic[df2['Assembly']]=df2['subtype']

In [254]:
df2.head()
import sys

In [266]:
for line in open("new_50gene.list"):
    line=line.rstrip()
    sys.stdout.write("\t"+line)
sys.stdout.write('\n')

for key1 in dic:
    sys.stdout.write(key1+"\t")
    for value in dic.get(key1):
        value=value.split(",")
        if key1 in value:
            number=value.split(",")[1]
            sys.stdout.write(number+"\t")

	lpg0028	lpg0078	lpg0116	lpg0212	lpg0287	lpg0330	lpg0356	lpg0432	lpg0461	lpg0513	lpg0577	lpg0656	lpg0712	lpg0785	lpg0840	lpg0888	lpg0956	lpg1144	lpg1178	lpg1206	lpg1283	lpg1340	lpg1398	lpg1452	lpg1511	lpg1566	lpg1636	lpg1682	lpg1737	lpg1782	lpg1830	lpg1882	lpg1994	lpg2039	lpg2175	lpg2231	lpg2280	lpg2339	lpg2404	lpg2461	lpg2516	lpg2577	lpg2622	lpg2698	lpg2743	lpg2795	lpg2827	lpg2869	lpg2933	lpg2999
GCF900051665	GCF900063035	GCF900054665	GCF900064765	GCF900062695	GCF900057605	GCF900054685	GCF900063835	GCF900062535	GCF900058835	GCF900062665	GCF900063145	GCF900059595	GCF900062735	GCF900063865	GCF900050245	GCF900064335	GCF900057615	GCF900060775	GCF900054385	GCF900048965	GCF900061675	GCF900063845	GCF900054695	GCF900062525	GCF900064755	GCF900064315	GCF900060425	GCF900053435	GCF900060435	GCF900056235	GCF900062675	GCF900061665	GCF900073035	GCF900062605	GCF900057785	GCF900064355	GCF900051755	GCF900061535	GCF900048955	GCF900063855	GCF900049285	GCF900060445	GCF900058825	GCF900060415	GCF900061475	GCF900061715	GCF900064345	GCF900054675	GCF900051675	GCF900055635	GCF900063885	GCF900057585	GCF900051015	GCF900052905	GCF900062565	GCF900052325	GCF900053745	GCF900062705	GCF900055585	GCF900065905	GCF900062575	GCF900062585	GCF900062555	GCF900064375	GCF900063895	GCF900063905	GCF900055215	GCF900062755	GCF900060015	GCF900061635	GCF900062715	GCF900061655	GCF900049275	GCF900058865	GCF900061975	GCF900051725	GCF900065445	GCF900063795	GCF900057595	GCF900052925	GCF900048915	GCF900063805	GCF900049375	GCF900056205	GCF900061485	GCF900054165	GCF900061565	GCF900056245	GCF900060195	GCF900054655	GCF900049295	GCF900064325	GCF900061725	GCF900061695	GCF900054395	GCF900050975	GCF900064365	GCF900054155	GCF900062875	GCF900061685	GCF900063125	GCF900051025	GCF900062725	GCF900056225	GCF900057575	GCF900052335	GCF900062545	GCF900063935	GCF900063915	GCF900062655	GCF900057745	GCF900060025	GCF900062645	GCF900063135	GCF900060795	GCF900060785	GCF900056215	GCF900053425	GCF900056935	GCF900064385	GCF900058855	GCF900060005	GCF900060455	GCF900063115	GCF900062625	GCF900050555	GCF900063925	GCF900054645	GCF900057265	GCF900061645	GCF900051745	GCF900055605	GCF900058845	GCF900058355	GCF900057625	GCF900062685	GCF900059605	GCF900062615	GCF900065915	GCF900061545	GCF900055615	GCF900058555	GCF900062745	GCF900064205	GCF900054435	GCF900073005	GCF900062635	GCF900051005	GCF900055625	GCF900057275	GCF900056945	GCF900053445	GCF900053665	GCF900056195	GCF900061705	GCF900062595	GCF900064495	GCF900049305	GCF900052265	GCF900063875	GCF900050195	GCF900063815	GCF900058605	GCF900052945	GCF900063065	GCF900057555	GCF900053685	GCF900049255	GCF900053695	GCF900060205	GCF900057545	GCF900051705	GCF900052915	GCF900051655	GCF900050175	GCF900061605	GCF900058575	GCF900058805	GCF900050235	GCF900057735	GCF900061585	GCF900051695	GCF900052065	GCF900048925	GCF900061505	GCF900064715	GCF900051715	GCF900053675	GCF900052935	GCF900052095	GCF900063785	GCF900060715	GCF900058565	GCF900062335	GCF900052075	GCF900062855	GCF900052275	GCF900050205	GCF900070125	GCF900059575	GCF900063045	GCF900052055	GCF900053705	GCF900060365	GCF900050215	GCF900050225	GCF900070165	GCF900059965	GCF900052255	GCF900061575	GCF900056645	GCF900057255	GCF900061595	GCF900059955	GCF900060385	GCF900053335	GCF900061495	GCF900059935	GCF900061515	GCF900057755	GCF900051685	GCF900060745	GCF900060735	GCF900061555	GCF900060725	GCF900057235	GCF900056915	GCF900061455	GCF900048905	GCF900070145	GCF900060375	GCF900052085	GCF900055575	GCF900062865	GCF900053405	GCF900062355	GCF900054415	GCF900062415	GCF900058595	GCF900073025	GCF900064735	GCF900062375	GCF900051735	GCF900054425	GCF900055205	GCF900053375	GCF900060395	GCF900062345	GCF900061625	GCF900062365	GCF900063085	GCF900050985	GCF900053725	GCF900062315	GCF900052305	GCF900049245	GCF900059985	GCF900065895	GCF900052295	GCF900065305	GCF900053715	GCF900061615	GCF900056185	GCF900050995	GCF900059995	GCF900062395	GCF900062405	GCF900052315	GCF900064485	GCF900053735	GCF900055195	GCF900053395	GCF900059975	GCF900057565	GCF900057765	GCF900059585	GCF900048945	GCF900050565	GCF900062445	GCF900062455	GCF900064745	GCF900073045	GCF900061945	GCF900065435	GCF900063105	GCF900063095	GCF900064195	GCF900053385	GCF900058815	GCF900060755	GCF900052105	GCF900064185	GCF900062425	GCF900062485	GCF900062435	GCF900070155	GCF900062475	GCF900055595	GCF900058585	GCF900053345	GCF900060405	GCF900062465	GCF900073055	GCF900063075	GCF900062325	GCF900058335	GCF900058345	GCF900061935	GCF900057775	GCF900062385	GCF900052285	GCF900063825	GCF900060765	GCF900060695	GCF900060705	GCF900064175	GCF900064725	GCF900062495	GCF900057245	GCF900065315	GCF900053415	GCF900056655	GCF900061465	GCF900062505	GCF900063055	GCF900053365	GCF900049265	GCF900070135	GCF900054405	GCF900062515	GCF900070185	GCF900050185	GCF900059945	GCF900056925	GCF900061525	GCF900048935	GCF900053355

In [ ]:
for key1 in dic:
    sys.stdout.write(key1+"\t")
    for value in dic.get(key1):